import { headers } from "next/headers";
import { redirect } from "next/navigation";
import Link from "next/link";
import { requireUser } from "@/lib/auth/server";
import { requireOrgAccess } from "@/lib/security/permissions";
import { withContext } from "@/lib/logging/request-context";
import { searchNotes } from "@/lib/search/actions";
import { PermissionDenied } from "@/components/permission-denied";
import { PageHeader } from "@/components/page-header";
import { EmptyState } from "@/components/empty-state";
import { ErrorAlert } from "@/components/error-alert";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Search, FileText, Clock } from "lucide-react";

function formatDate(d: Date) {
  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(d);
}

export default async function SearchPage({
  searchParams,
}: {
  searchParams: Promise<{ q?: string }>;
}) {
  let user;
  try {
    user = await requireUser();
  } catch {
    redirect("/login");
  }

  const h = await headers();
  const orgId = h.get("x-org-id");
  if (!orgId) redirect("/org/create");
  const requestId = h.get("x-request-id") ?? "unknown";

  try {
    await withContext({ requestId, orgId, userId: user.id }, () =>
      requireOrgAccess(orgId, "viewer"),
    );
  } catch {
    return <PermissionDenied />;
  }

  const { q = "" } = await searchParams;
  const trimmedQ = q.trim();

  let results: Awaited<ReturnType<typeof searchNotes>> = [];
  let searchError: string | null = null;

  if (trimmedQ) {
    try {
      results = await searchNotes({ query: trimmedQ, limit: 20, offset: 0 });
    } catch (err) {
      searchError = err instanceof Error ? err.message : "Search failed";
    }
  }

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <PageHeader title="Search" />

      <form method="GET" action="/search" className="flex gap-2">
        <Input
          name="q"
          defaultValue={q}
          placeholder="Search notes…"
          className="flex-1"
          autoFocus
        />
        <Button type="submit">
          <Search className="h-4 w-4 mr-1" />
          Search
        </Button>
      </form>

      {searchError && <ErrorAlert message={searchError} />}

      {trimmedQ && !searchError && (
        <>
          <div className="flex items-center text-sm text-muted-foreground">
            <span>
              {results.length === 0
                ? "No results"
                : `${results.length} result${results.length === 1 ? "" : "s"}`}
              {" "}for{" "}
              <span className="font-medium text-foreground">
                &ldquo;{trimmedQ}&rdquo;
              </span>
            </span>
          </div>

          {results.length === 0 ? (
            <EmptyState
              title="No notes found"
              description={`No notes match "${trimmedQ}". Try different keywords.`}
            />
          ) : (
            <div className="divide-y divide-border rounded-md border">
              {results.map((note) => (
                <Link
                  key={note.id}
                  href={`/notes/${note.id}`}
                  className="flex flex-col gap-1.5 p-4 hover:bg-muted/40 transition-colors"
                >
                  <div className="flex items-center gap-2 min-w-0">
                    <FileText className="h-4 w-4 shrink-0 text-muted-foreground" />
                    <span className="font-medium text-sm truncate">
                      {note.title || "Untitled"}
                    </span>
                  </div>
                  {note.snippet && (
                    <p
                      className="text-sm text-muted-foreground line-clamp-2 pl-6 [&_mark]:bg-yellow-100 [&_mark]:text-yellow-900 [&_mark]:rounded-sm [&_mark]:px-0.5"
                      // snippet is server-generated by ts_headline with fixed <mark> tags
                      dangerouslySetInnerHTML={{ __html: note.snippet }}
                    />
                  )}
                  <div className="flex items-center gap-1 text-xs text-muted-foreground pl-6">
                    <Clock className="h-3 w-3" />
                    <span>{formatDate(note.updatedAt)}</span>
                  </div>
                </Link>
              ))}
            </div>
          )}
        </>
      )}

      {!trimmedQ && !searchError && (
        <EmptyState
          title="Find anything"
          description="Type a query above to search across all notes in your workspace."
        />
      )}
    </div>
  );
}
